version: 2.1

jobs:
  deploy:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Install Ansible
          command: pip install ansible
      - add_ssh_keys:
          fingerprints:
            - "SHA256:s8D7dwC1OE/i7jdalIq1FWhpf+5xdGQ8pyBtEu4ByIA"
      - run:
          name: Run Ansible Playbook
          command: ansible-playbook -i inventory.ini deploy.yml
workflows:
  version: 2
  deploy:
    jobs:
      - deploy
